### ISSUE TITLE
[verifiable-credential]: version error in did-jwt dependency

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#118]
### Problem:

I tried to link the `@verida/verifiable-credentials` packages locally in my machine in order to test with on of our demos,

but it an throws error which prevents the vue app to start.

previous `did-jwt` version `5.12.1`. downgraded to `5.7.0` still having same issues

<img width="1234" alt="Screenshot 2021-12-12 at 07 36 49" src="https://user-images.githubusercontent.com/54280620/145703121-a3f52374-6787-4458-879b-aeccd9282701.png">

### How to reproduce the error

- Cd to the `verifiable-credential` folder
-  Yarn link `@verida/verifiable-credentials` in the folder
- Clone the [credential-scanner-demo]( https://github.com/verida/credential-scanner-web) and check to `1-update-libraries` branch 
- Yarn link `@verida/verifiable-credentials`
- Start the demo app `npm run serve`

**Comment by tahpot** [comment]
@cmcWebCode40

I'm pretty sure you haven't correctly downgraded to `5.7.0`. I had similar issues.

Also, make sure all the `@verida` packages in the demo is using the latest versions from npm.

**Comment by tahpot** [comment]
One way to check the actual version installed is to look in the `yarn.lock` file of your demo project.

**Comment by cmcWebCode40** [comment]
@taphot here is a branch `feature/118-downgrade-didjwt-package` i have committed where I downgraded the `didjwt` package

**Comment by tahpot** [comment]
@cmcWebCode40 I need a way to reproduce this on my local machine.

Can you please provide instructions.

Does your `yarn.lock` file have an entry for `did-jwt@^5.12.1` or just `did-jwt@^5.7.0`? If it has `5.12.1`, then there's an issue with the dependencies in local `verida-js` monorepo.

**Comment by cmcWebCode40** [comment]
ok, i will do now

**Comment by tahpot** [comment]
>Start the demo app `npm run serve`

We are using `npm`, so this won't work correctly (the `yarn link` doesn't attach to `npm` as they run independently). I noticed you have been running `npm` as it has a `package-lock.json` file which is only used by `npm`.

I deleted `package-lock.json`, then ran `yarn install` to fetch the latest packages.

However, it still doesn't work and I get the same error message :(

I did a [quick Google](https://www.google.com/search?q=vuejs+unexpected+token+appropriate+loader&oq=vuejs+unexpected+token+appropriate+loader&aqs=chrome..69i57.8512j0j1&sourceid=chrome&ie=UTF-8) and it appears there is a webpack configuration issue with Vuejs.

Hopefully you can investigate that further and see if you can fix the Vue configuration?

Perhaps try adding the credential library to a more recent demo and see if it works? (markdown editor)

You may need to upgrade VueJs in that project to the very latest if you haven't already.

**Comment by cmcWebCode40** [comment]
> Perhaps try adding the credential library to a more recent demo and see if it works? (markdown editor)

I actually tested with the markdown editor that was running on `yarn` but still got the same error. 

> Hopefully you can investigate that further and see if you can fix the Vue configuration?
 I will investigate  regarding the vue configurations

**Comment by tahpot** [comment]
@cmcWebCode40 

Yeah, we previously had the same issue here: https://github.com/verida/markdown-notes-demo/pull/97

That time it was caused because the `@verida` libraries were pointing to the newer version of `did-jwt`. Not sure why it's happening now.

**Comment by cmcWebCode40** [comment]
@tahpot , 

i have been investigating , so far these are what I have been able to achieve

### Cause of the error

from the `node_modules` folder i found out that the `did-jwt-vc` library uses `did-jwt` lastest version `5.12.1` as a dependency  in its package.json file

I had to downgrade the `did-jwt-vc` library to use version `1.2.0`  which downgraded the `did-jwt` to version `4.9.0` , at the moment i don't get the error anymore , it works now except for when i want to call this method from the  `Credentials` class 
`verifyCredential()` to verify a credential. 
it  throws this error :

```
Error: DID document for did:vda:0x28b3DDeC3fDA534D3599A0bf195bB7461cEc0853 does not have public keys for ES256K
```

**Comment by tahpot** [comment]
There's an issue here that looks similar: https://github.com/decentralized-identity/did-jwt/issues/168

This is interesting:

>However, I am guessing that this module, did-jwt, has not been transpiled from ES6 to ES5, and thus causes this error. 

Perhaps VueJs is expecting ES5 and `did-jwt` is compiling to ES6 or something?

**Comment by cmcWebCode40** [comment]
> If that syntax error in did-jwt version 5.12.1 is the only error, maybe it would be easier to fork did-jwt, change than line and submit a PR?  

Yes but that's means I have to understand the `did-jwt` well before I could modify and open PR

**Comment by cmcWebCode40** [comment]
> Perhaps VueJs is expecting ES5 and did-jwt is compiling to ES6 or something?

That could be possible, i will have to continue investigating

**Comment by nick-verida** [comment]
Hey @kalanamt adding you to this because we'd like you to look at this at some point (not an immediate priority)

**Comment by tahpot** [comment]
I did some testing to further investigate this issue.

I reset my local version of `credential-scanner-web`:

- `rm -rf node_modules`
- Removed all verida dependencies from `package.json`
- Deleted `yarn.lock`
- Re-ran `yarn` to install all dependencies
- Checked out `feature/118-downgrade-didjwt-package` from `@verida/verida-js`
- `yarn build` on `@verida` / `account-web-vault`, `client-ts`, `encryption-utils`, `verifiable-credentials`
- `yarn linked` all `@verida` dependencies (as above)

After running `yarn run serve` the error still appears.

Upon closer investigation it appears that `verifiable-credentials/node_modules/did-jwt` is including code from `did-jwt@5.12.0`, instead of the expected `did-jwt@5.7.0`. This was established by checking the code in github for those versions against the code in `verifiable-credentials/node_modules/did-jwt/index.module.js`.

A search of `verida-js/yarn.lock` shows no reference to any version of `did-jwt` that isn't `5.7.0`.

Why is `yarn` including the incorrect version of `did-jwt` in `@verida/verifiable-credentials`?

**Comment by tahpot** [comment]
An update to this.

The latest version of `did-jwt-vc` refers to the new version of `did-jwt` which is causing this issue.

I attempted to downgrade `did-jwt-vc` to `2.1.7` because it's `yarn.lock` refers to `did-jwt@5.7.0` (https://github.com/decentralized-identity/did-jwt-vc/blob/9cce8e19825bc2489b0d7c820e282746d4ae5cdb/yarn.lock#L4045), however yarn is still including the newer version of `did-jwt` when running `yarn add "did-jwt-vc@2.7.1"`

**Comment by cmcWebCode40** [comment]
This was actually the main issue with the `did-jwt-vc` package it refers to the latest version of `did-jwt`

**Comment by cmcWebCode40** [comment]
> Why is yarn including the incorrect version of did-jwt in @verida/verifiable-credentials?

Not sure about that but I did downgrade to the `5.7.0` ( https://github.com/verida/verida-js/commit/f11f43bdfdac70044c5f6023143c9b0d69da4189) when i reported this issue

**Comment by tahpot** [comment]
The issue is caused by a double question mark `"??"` which is ES2020 syntax. For some reason, that isn't being compiled correctly.

We should that fix issue and then use the latest versions of the `did-jwt` and `did-jwt-vc` libraries.

@kalanamt will find a solution :)

**Comment by nick-verida** [comment]
@kalanamt can you add an update on this one?

**Comment by kalanamt** [comment]
Haven't started yet on this , So far I have been working on 
* https://github.com/verida/did-server/issues/15
* https://github.com/verida/practitioner-emr-web/issues/7
* https://github.com/verida/verida-js/issues/127
* Notification server understanding how it works and fixed non executing async loop

**Comment by kalanamt** [comment]
@nick-verida  We might need to update Node 16 as a fix for this

**Comment by nick-verida** [comment]
> @nick-verida We might need to update Node 16 as a fix for this

Can you provide further details?

**Comment by kalanamt** [comment]
This `"??"` does not supported by the current node version , and its been used in one of the libraries . Will provide more information once I started to work on this . Ref :- https://github.com/verida/verida-js/issues/118#issuecomment-1014113635

**Comment by nick-verida** [comment]
This isn't an issue with `verida-js`

The problem is that the webpack version in https://github.com/verida/credential-scanner-web doesn't support the "stage3" JS features required. 

I believe it is possible to fix this with a `babel.config.js` setting, but I couldn't get this to work. However by changing the resolve used by Webpack as noted here: https://github.com/OnurGvnc/acorn-with-stage3 it works.

**Comment by nick-verida** [comment]
I'll wait for @cmcWebCode40  to confirm this he can use `credential-scanner-web`, but I believe this issue can be closed.

**Comment by nick-verida** [comment]
This is now fixed
